# Generated by Django 5.0.2 on 2024-04-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fcc_api', '0004_rename_areas_de_trabajo_maestros_areas_de_trabajo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='materias',
            new_name='materias_json',
        ),
    ]
