# Generated by Django 5.0.2 on 2024-04-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fcc_api', '0007_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='horario_finalizacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='programa_educativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='salon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
