# Generated by Django 5.0.2 on 2024-04-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fcc_api', '0008_materia_horario_finalizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nrc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='salon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='seccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
