# Generated by Django 5.0.2 on 2024-05-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fcc_api', '0009_alter_materia_nrc_alter_materia_salon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nrc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
