# Generated by Django 5.0.2 on 2024-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fcc_api', '0010_alter_materia_nrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='seccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
